/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package longestRepeatedString

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App("jamesalbjamesalbersheim")
        assertEquals(classUnderTest.repeat, "jamesalb")
    }
}
