/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package longestRepeatedString

import livongo.albersheim.*

class App(val input: String) {
    val repeat: String
        get() {
            var repeatString: RepeatStringInterface = RepeatString()
            return repeatString.findLongestRepeatingSubstring(input)
        }
}

fun main(args: Array<String>) {
    println(App(args[0]).repeat)
}
